name: Get Link

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک یوتیوب'
        required: true

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - run: pip install yt-dlp
      - run: yt-dlp -g -f "best[height<=720]" "${{ inputs.url }}"
